# Libraries and Functions

In [ ]:
#Importing libraries
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
pd.options.display.max_rows = 999
import warnings
warnings.filterwarnings("ignore")
import sys
sys.dont_write_bytecode = True
#importing datasets
from src.New_Utils import New_Sequences
from Datasets import Replace
from Datasets import AIDE
from Datasets import Shanghai
#Libraries to run the experiments
from src.model import Model
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

In [13]:
Model = Model()

In [17]:
def Run_Models(sequences, l1_penalty, l2_penalty, learning_rate, batch_size,  skf, Model):

    model = Model
    results = []

    # loop across the folds
    for i, (train_index, test_index) in enumerate(skf.split(X=[s['X'] for s in sequences], y=[s['Y'] for s in sequences])):
        
        # fit the model to the training set


        model.fit(
            sequences=[sequences[i] for i in train_index],
            sequence_length=int(7 * 24 * 60 // 5),
            l1_penalty=l1_penalty,
            l2_penalty=l2_penalty,
            learning_rate=learning_rate,
            batch_size=batch_size,
            epochs=1000,
            seed=42,
            verbose=0
        )

        # evaluate the model on the test set
        metrics = model.evaluate(sequences=[sequences[i] for i in test_index])

        # save the results
        results.append(metrics)

    # organize the results in a data frame
    results = pd.DataFrame(results)

    return results.mean().values[6]

# Grid Search

In [5]:
Parameters =[[0.01, 0.01, 1e-06, 64]
,[0.01, 0.01, 1e-06, 32]
,[0.01, 0.01, 1e-06, 16]
,[0.01, 0.01, 1e-06, 128]
,[0.01, 0.01, 0.1, 64]
,[0.01, 0.01, 0.1, 32]
,[0.01, 0.01, 0.1, 16]
,[0.01, 0.01, 0.1, 128]
,[0.01, 0.01, 0.0001, 64]
,[0.01, 0.01, 0.0001, 32]
,[0.01, 0.01, 0.0001, 16]
,[0.01, 0.01, 0.0001, 128]
,[0.01, 0.001, 1e-06, 64]
,[0.01, 0.001, 1e-06, 32]
,[0.01, 0.001, 1e-06, 16]
,[0.01, 0.001, 1e-06, 128]
,[0.01, 0.001, 0.1, 64]
,[0.01, 0.001, 0.1, 32]
,[0.01, 0.001, 0.1, 16]
,[0.01, 0.001, 0.1, 128]
,[0.01, 0.001, 0.0001, 64]
,[0.01, 0.001, 0.0001, 32]
,[0.01, 0.001, 0.0001, 16]
,[0.01, 0.001, 0.0001, 128]
,[0.01, 0.0001, 1e-06, 64]
,[0.01, 0.0001, 1e-06, 32]
,[0.01, 0.0001, 1e-06, 16]
,[0.01, 0.0001, 1e-06, 128]
,[0.01, 0.0001, 0.1, 64]
,[0.01, 0.0001, 0.1, 32]
,[0.01, 0.0001, 0.1, 16]
,[0.01, 0.0001, 0.1, 128]
,[0.01, 0.0001, 0.0001, 64]
,[0.01, 0.0001, 0.0001, 32]
,[0.01, 0.0001, 0.0001, 16]
,[0.01, 0.0001, 0.0001, 128]
,[0.001, 0.01, 1e-06, 64]
,[0.001, 0.01, 1e-06, 32]
,[0.001, 0.01, 1e-06, 16]
,[0.001, 0.01, 1e-06, 128]
,[0.001, 0.01, 0.1, 64]
,[0.001, 0.01, 0.1, 32]
,[0.001, 0.01, 0.1, 16]
,[0.001, 0.01, 0.1, 128]
,[0.001, 0.01, 0.0001, 64]
,[0.001, 0.01, 0.0001, 32]
,[0.001, 0.01, 0.0001, 16]
,[0.001, 0.01, 0.0001, 128]
,[0.001, 0.001, 1e-06, 64]
,[0.001, 0.001, 1e-06, 32]
,[0.001, 0.001, 1e-06, 16]
,[0.001, 0.001, 1e-06, 128]
,[0.001, 0.001, 0.1, 64]
,[0.001, 0.001, 0.1, 32]
,[0.001, 0.001, 0.1, 16]
,[0.001, 0.001, 0.1, 128]
,[0.001, 0.001, 0.0001, 64]
,[0.001, 0.001, 0.0001, 32]
,[0.001, 0.001, 0.0001, 16]
,[0.001, 0.001, 0.0001, 128]
,[0.001, 0.0001, 1e-06, 64]
,[0.001, 0.0001, 1e-06, 32]
,[0.001, 0.0001, 1e-06, 16]
,[0.001, 0.0001, 1e-06, 128]
,[0.001, 0.0001, 0.1, 64]
,[0.001, 0.0001, 0.1, 32]
,[0.001, 0.0001, 0.1, 16]
,[0.001, 0.0001, 0.1, 128]
,[0.001, 0.0001, 0.0001, 64]
,[0.001, 0.0001, 0.0001, 32]
,[0.001, 0.0001, 0.0001, 16]
,[0.001, 0.0001, 0.0001, 128]
,[0.0001, 0.01, 1e-06, 64]
,[0.0001, 0.01, 1e-06, 32]
,[0.0001, 0.01, 1e-06, 16]
,[0.0001, 0.01, 1e-06, 128]
,[0.0001, 0.01, 0.1, 64]
,[0.0001, 0.01, 0.1, 32]
,[0.0001, 0.01, 0.1, 16]
,[0.0001, 0.01, 0.1, 128]
,[0.0001, 0.01, 0.0001, 64]
,[0.0001, 0.01, 0.0001, 32]
,[0.0001, 0.01, 0.0001, 16]
,[0.0001, 0.01, 0.0001, 128]
,[0.0001, 0.001, 1e-06, 64]
,[0.0001, 0.001, 1e-06, 32]
,[0.0001, 0.001, 1e-06, 16]
,[0.0001, 0.001, 1e-06, 128]
,[0.0001, 0.001, 0.1, 64]
,[0.0001, 0.001, 0.1, 32]
,[0.0001, 0.001, 0.1, 16]
,[0.0001, 0.001, 0.1, 128]
,[0.0001, 0.001, 0.0001, 64]
,[0.0001, 0.001, 0.0001, 32]
,[0.0001, 0.001, 0.0001, 16]
,[0.0001, 0.001, 0.0001, 128]
,[0.0001, 0.0001, 1e-06, 64]
,[0.0001, 0.0001, 1e-06, 32]
,[0.0001, 0.0001, 1e-06, 16]
,[0.0001, 0.0001, 1e-06, 128]
,[0.0001, 0.0001, 0.1, 64]
,[0.0001, 0.0001, 0.1, 32]
,[0.0001, 0.0001, 0.1, 16]
,[0.0001, 0.0001, 0.1, 128]
,[0.0001, 0.0001, 0.0001, 64]
,[0.0001, 0.0001, 0.0001, 32]
,[0.0001, 0.0001, 0.0001, 16]
,[0.0001, 0.0001, 0.0001, 128]
]

## Replace

In [ ]:
sequences = New_Sequences(Replace)
Grid_Search_Results = pd.DataFrame(columns=['Parameters','AUC'])
for params in Parameters:
    l1_penalty, l2_penalty, learning_rate, batch_size = params
    try:
        R = Run_Models(sequences, l1_penalty,l2_penalty,learning_rate,batch_size, skf, Model)
        Grid_Search_Results = pd.concat([Grid_Search_Results, pd.DataFrame({
            'Parameters': [str(params)], 
            'AUC': [R]
        })], ignore_index=True)
    except Exception as e:
        print(f"Error con parámetros {params}: {e}")
        continue
Grid_Search_Results.sort_values(by='AUC', ascending=False)

## AIDE

In [ ]:
sequences = New_Sequences(AIDE)
Grid_Search_Results = pd.DataFrame(columns=['Parameters','AUC'])
for params in Parameters:
    l1_penalty, l2_penalty, learning_rate, batch_size = params
    try:
        R = Run_Models(sequences, l1_penalty,l2_penalty,learning_rate,batch_size, skf, Model)
        Grid_Search_Results = pd.concat([Grid_Search_Results, pd.DataFrame({
            'Parameters': [str(params)], 
            'AUC': [R]
        })], ignore_index=True)
    except Exception as e:
        print(f"Error con parámetros {params}: {e}")
        continue
Grid_Search_Results.sort_values(by='AUC', ascending=False)

Error con parámetros [0.01, 0.01, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'

Empty DataFrame
Columns: [Parameters, AUC]
Index: []

# Shanghai

In [21]:
sequences = New_Sequences(Shanghai, minutes=15)
Grid_Search_Results = pd.DataFrame(columns=['Parameters','AUC'])
for params in Parameters:
    l1_penalty, l2_penalty, learning_rate, batch_size = params
    try:
        R = Run_Models(sequences, l1_penalty,l2_penalty,learning_rate,batch_size, skf, Model)
        Grid_Search_Results = pd.concat([Grid_Search_Results, pd.DataFrame({
            'Parameters': [str(params)], 
            'AUC': [R]
        })], ignore_index=True)
    except Exception as e:
        print(f"Error con parámetros {params}: {e}")
        continue
Grid_Search_Results.sort_values(by='AUC', ascending=False)

                        Parameters       AUC
102      [0.0001, 0.0001, 0.1, 16]      0.75
54         [0.001, 0.001, 0.1, 16]  0.714286
66        [0.001, 0.0001, 0.1, 16]  0.702381
7           [0.01, 0.01, 0.1, 128]  0.690476
4            [0.01, 0.01, 0.1, 64]  0.690476
5            [0.01, 0.01, 0.1, 32]  0.690476
42          [0.001, 0.01, 0.1, 16]  0.613095
67       [0.001, 0.0001, 0.1, 128]  0.607143
64        [0.001, 0.0001, 0.1, 64]  0.607143
65        [0.001, 0.0001, 0.1, 32]  0.607143
105   [0.0001, 0.0001, 0.0001, 32]  0.595238
44       [0.001, 0.01, 0.0001, 64]  0.595238
45       [0.001, 0.01, 0.0001, 32]  0.595238
47      [0.001, 0.01, 0.0001, 128]  0.595238
52         [0.001, 0.001, 0.1, 64]  0.595238
53         [0.001, 0.001, 0.1, 32]  0.595238
55        [0.001, 0.001, 0.1, 128]  0.595238
56      [0.001, 0.001, 0.0001, 64]  0.595238
57      [0.001, 0.001, 0.0001, 32]  0.595238
59     [0.001, 0.001, 0.0001, 128]  0.595238
104   [0.0001, 0.0001, 0.0001, 64]  0.595238
95    [0.0001, 0.001, 0.0001, 128]  0.595238
68     [0.001, 0.0001, 0.0001, 64]  0.595238
69     [0.001, 0.0001, 0.0001, 32]  0.595238
35     [0.01, 0.0001, 0.0001, 128]  0.595238
80      [0.0001, 0.01, 0.0001, 64]  0.595238
81      [0.0001, 0.01, 0.0001, 32]  0.595238
83     [0.0001, 0.01, 0.0001, 128]  0.595238
88        [0.0001, 0.001, 0.1, 64]  0.595238
89        [0.0001, 0.001, 0.1, 32]  0.595238
91       [0.0001, 0.001, 0.1, 128]  0.595238
92     [0.0001, 0.001, 0.0001, 64]  0.595238
93     [0.0001, 0.001, 0.0001, 32]  0.595238
71    [0.001, 0.0001, 0.0001, 128]  0.595238
107  [0.0001, 0.0001, 0.0001, 128]  0.595238
9         [0.01, 0.01, 0.0001, 32]  0.595238
8         [0.01, 0.01, 0.0001, 64]  0.595238
18          [0.01, 0.001, 0.1, 16]  0.595238
20       [0.01, 0.001, 0.0001, 64]  0.595238
21       [0.01, 0.001, 0.0001, 32]  0.595238
23      [0.01, 0.001, 0.0001, 128]  0.595238
33      [0.01, 0.0001, 0.0001, 32]  0.595238
32      [0.01, 0.0001, 0.0001, 64]  0.595238
11       [0.01, 0.01, 0.0001, 128]  0.595238
30         [0.01, 0.0001, 0.1, 16]  0.583333
22       [0.01, 0.001, 0.0001, 16]  0.559524
90        [0.0001, 0.001, 0.1, 16]  0.559524
10        [0.01, 0.01, 0.0001, 16]  0.559524
34      [0.01, 0.0001, 0.0001, 16]  0.559524
103     [0.0001, 0.0001, 0.1, 128]  0.559524
101      [0.0001, 0.0001, 0.1, 32]  0.559524
100      [0.0001, 0.0001, 0.1, 64]  0.559524
79        [0.0001, 0.01, 0.1, 128]  0.541667
77         [0.0001, 0.01, 0.1, 32]  0.541667
76         [0.0001, 0.01, 0.1, 64]  0.541667
6            [0.01, 0.01, 0.1, 16]   0.52381
58      [0.001, 0.001, 0.0001, 16]   0.52381
46       [0.001, 0.01, 0.0001, 16]   0.52381
70     [0.001, 0.0001, 0.0001, 16]   0.52381
31        [0.01, 0.0001, 0.1, 128]  0.494048
28         [0.01, 0.0001, 0.1, 64]  0.494048
29         [0.01, 0.0001, 0.1, 32]  0.494048
94     [0.0001, 0.001, 0.0001, 16]  0.488095
106   [0.0001, 0.0001, 0.0001, 16]  0.488095
82      [0.0001, 0.01, 0.0001, 16]  0.488095
14        [0.01, 0.001, 1e-06, 16]   0.47619
84      [0.0001, 0.001, 1e-06, 64]   0.47619
85      [0.0001, 0.001, 1e-06, 32]   0.47619
86      [0.0001, 0.001, 1e-06, 16]   0.47619
99    [0.0001, 0.0001, 1e-06, 128]   0.47619
87     [0.0001, 0.001, 1e-06, 128]   0.47619
2          [0.01, 0.01, 1e-06, 16]   0.47619
3         [0.01, 0.01, 1e-06, 128]   0.47619
98     [0.0001, 0.0001, 1e-06, 16]   0.47619
13        [0.01, 0.001, 1e-06, 32]   0.47619
12        [0.01, 0.001, 1e-06, 64]   0.47619
96     [0.0001, 0.0001, 1e-06, 64]   0.47619
97     [0.0001, 0.0001, 1e-06, 32]   0.47619
15       [0.01, 0.001, 1e-06, 128]   0.47619
0          [0.01, 0.01, 1e-06, 64]   0.47619
26       [0.01, 0.0001, 1e-06, 16]   0.47619
60      [0.001, 0.0001, 1e-06, 64]   0.47619
48       [0.001, 0.001, 1e-06, 64]   0.47619
49       [0.001, 0.001, 1e-06, 32]   0.47619
50       [0.001, 0.001, 1e-06, 16]   0.47619
51      [0.001, 0.001, 1e-06, 128]   0.47619
1          [0.01, 0.01, 1e-06, 32]   0.47619
27      [0.01, 0.0001, 1e-06, 128]   0.47619
38        [0.001, 0.01, 1e-06, 16]   0.47619
25       [0.01, 0.0001, 1e-06, 32]   0.47619
39       [0.001, 0.01, 1e-06, 128]   0.47619
24       [0.01, 0.0001, 1e-06, 64]   0.47619
61      [0.001, 0.0001, 1e-06, 32]   0.47619
62      [0.001, 0.0001, 1e-06, 16]   0.47619
63     [0.001, 0.0001, 1e-06, 128]   0.47619
37        [0.001, 0.01, 1e-06, 32]   0.47619
36        [0.001, 0.01, 1e-06, 64]   0.47619
72       [0.0001, 0.01, 1e-06, 64]   0.47619
73       [0.0001, 0.01, 1e-06, 32]   0.47619
74       [0.0001, 0.01, 1e-06, 16]   0.47619
75      [0.0001, 0.01, 1e-06, 128]   0.47619
43         [0.001, 0.01, 0.1, 128]  0.416667
41          [0.001, 0.01, 0.1, 32]  0.416667
40          [0.001, 0.01, 0.1, 64]  0.416667
16          [0.01, 0.001, 0.1, 64]  0.410714
19         [0.01, 0.001, 0.1, 128]  0.410714
17          [0.01, 0.001, 0.1, 32]  0.410714
78         [0.0001, 0.01, 0.1, 16]  0.363095

# Random Search

In [22]:
Parameter = [[0.9447, 0.7984, 0.9425, 64]
,[0.9447, 0.7984, 0.9425, 32]
,[0.9447, 0.7984, 0.9425, 16]
,[0.9447, 0.7984, 0.9425, 128]
,[0.9447, 0.7984, 0.3126, 64]
,[0.9447, 0.7984, 0.3126, 32]
,[0.9447, 0.7984, 0.3126, 16]
,[0.9447, 0.7984, 0.3126, 128]
,[0.9447, 0.7984, 0.0916, 64]
,[0.9447, 0.7984, 0.0916, 32]
,[0.9447, 0.7984, 0.0916, 16]
,[0.9447, 0.7984, 0.0916, 128]
,[0.9447, 0.5364, 0.9425, 64]
,[0.9447, 0.5364, 0.9425, 32]
,[0.9447, 0.5364, 0.9425, 16]
,[0.9447, 0.5364, 0.9425, 128]
,[0.9447, 0.5364, 0.3126, 64]
,[0.9447, 0.5364, 0.3126, 32]
,[0.9447, 0.5364, 0.3126, 16]
,[0.9447, 0.5364, 0.3126, 128]
,[0.9447, 0.5364, 0.0916, 64]
,[0.9447, 0.5364, 0.0916, 32]
,[0.9447, 0.5364, 0.0916, 16]
,[0.9447, 0.5364, 0.0916, 128]
,[0.9447, 0.5143, 0.9425, 64]
,[0.9447, 0.5143, 0.9425, 32]
,[0.9447, 0.5143, 0.9425, 16]
,[0.9447, 0.5143, 0.9425, 128]
,[0.9447, 0.5143, 0.3126, 64]
,[0.9447, 0.5143, 0.3126, 32]
,[0.9447, 0.5143, 0.3126, 16]
,[0.9447, 0.5143, 0.3126, 128]
,[0.9447, 0.5143, 0.0916, 64]
,[0.9447, 0.5143, 0.0916, 32]
,[0.9447, 0.5143, 0.0916, 16]
,[0.9447, 0.5143, 0.0916, 128]
,[0.6265, 0.7984, 0.9425, 64]
,[0.6265, 0.7984, 0.9425, 32]
,[0.6265, 0.7984, 0.9425, 16]
,[0.6265, 0.7984, 0.9425, 128]
,[0.6265, 0.7984, 0.3126, 64]
,[0.6265, 0.7984, 0.3126, 32]
,[0.6265, 0.7984, 0.3126, 16]
,[0.6265, 0.7984, 0.3126, 128]
,[0.6265, 0.7984, 0.0916, 64]
,[0.6265, 0.7984, 0.0916, 32]
,[0.6265, 0.7984, 0.0916, 16]
,[0.6265, 0.7984, 0.0916, 128]
,[0.6265, 0.5364, 0.9425, 64]
,[0.6265, 0.5364, 0.9425, 32]
,[0.6265, 0.5364, 0.9425, 16]
,[0.6265, 0.5364, 0.9425, 128]
,[0.6265, 0.5364, 0.3126, 64]
,[0.6265, 0.5364, 0.3126, 32]
,[0.6265, 0.5364, 0.3126, 16]
,[0.6265, 0.5364, 0.3126, 128]
,[0.6265, 0.5364, 0.0916, 64]
,[0.6265, 0.5364, 0.0916, 32]
,[0.6265, 0.5364, 0.0916, 16]
,[0.6265, 0.5364, 0.0916, 128]
,[0.6265, 0.5143, 0.9425, 64]
,[0.6265, 0.5143, 0.9425, 32]
,[0.6265, 0.5143, 0.9425, 16]
,[0.6265, 0.5143, 0.9425, 128]
,[0.6265, 0.5143, 0.3126, 64]
,[0.6265, 0.5143, 0.3126, 32]
,[0.6265, 0.5143, 0.3126, 16]
,[0.6265, 0.5143, 0.3126, 128]
,[0.6265, 0.5143, 0.0916, 64]
,[0.6265, 0.5143, 0.0916, 32]
,[0.6265, 0.5143, 0.0916, 16]
,[0.6265, 0.5143, 0.0916, 128]
,[0.146, 0.7984, 0.9425, 64]
,[0.146, 0.7984, 0.9425, 32]
,[0.146, 0.7984, 0.9425, 16]
,[0.146, 0.7984, 0.9425, 128]
,[0.146, 0.7984, 0.3126, 64]
,[0.146, 0.7984, 0.3126, 32]
,[0.146, 0.7984, 0.3126, 16]
,[0.146, 0.7984, 0.3126, 128]
,[0.146, 0.7984, 0.0916, 64]
,[0.146, 0.7984, 0.0916, 32]
,[0.146, 0.7984, 0.0916, 16]
,[0.146, 0.7984, 0.0916, 128]
,[0.146, 0.5364, 0.9425, 64]
,[0.146, 0.5364, 0.9425, 32]
,[0.146, 0.5364, 0.9425, 16]
,[0.146, 0.5364, 0.9425, 128]
,[0.146, 0.5364, 0.3126, 64]
,[0.146, 0.5364, 0.3126, 32]
,[0.146, 0.5364, 0.3126, 16]
,[0.146, 0.5364, 0.3126, 128]
,[0.146, 0.5364, 0.0916, 64]
,[0.146, 0.5364, 0.0916, 32]
,[0.146, 0.5364, 0.0916, 16]
,[0.146, 0.5364, 0.0916, 128]
,[0.146, 0.5143, 0.9425, 64]
,[0.146, 0.5143, 0.9425, 32]
,[0.146, 0.5143, 0.9425, 16]
,[0.146, 0.5143, 0.9425, 128]
,[0.146, 0.5143, 0.3126, 64]
,[0.146, 0.5143, 0.3126, 32]
,[0.146, 0.5143, 0.3126, 16]
,[0.146, 0.5143, 0.3126, 128]
,[0.146, 0.5143, 0.0916, 64]
,[0.146, 0.5143, 0.0916, 32]
,[0.146, 0.5143, 0.0916, 16]
,[0.146, 0.5143, 0.0916, 128]]

## Replace

In [23]:
sequences = New_Sequences(Replace)
Randomized_Search_Results = pd.DataFrame(columns=['Parameters','AUC'])
for params in Parameters:
    l1_penalty, l2_penalty, learning_rate, batch_size = params
    try:
        R = Run_Models(sequences, l1_penalty,l2_penalty,learning_rate,batch_size, skf, Model)
        Randomized_Search_Results = pd.concat([Randomized_Search_Results, pd.DataFrame({
            'Parameters': [str(params)], 
            'AUC': [R]
        })], ignore_index=True)
    except Exception as e:
        print(f"Error con parámetros {params}: {e}")
        continue
Randomized_Search_Results.sort_values(by='AUC', ascending=False)

KeyboardInterrupt:

## AIDE

In [ ]:
sequences = New_Sequences(AIDE)
Randomized_Search_Results = pd.DataFrame(columns=['Parameters','AUC'])
for params in Parameters:
    l1_penalty, l2_penalty, learning_rate, batch_size = params
    try:
        R = Run_Models(sequences, l1_penalty,l2_penalty,learning_rate,batch_size, skf, Model)
        Randomized_Search_Results = pd.concat([Randomized_Search_Results, pd.DataFrame({
            'Parameters': [str(params)], 
            'AUC': [R]
        })], ignore_index=True)
    except Exception as e:
        print(f"Error con parámetros {params}: {e}")
        continue
Randomized_Search_Results.sort_values(by='AUC', ascending=False)

Error con parámetros [0.01, 0.01, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.01, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.01, 0.0001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.01, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.001, 0.0001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.01, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 1e-06, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 1e-06, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 1e-06, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 1e-06, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.1, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.1, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.1, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.1, 128]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.0001, 64]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.0001, 32]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.0001, 16]: Model.fit() missing 1 required positional argument: 'self'
Error con parámetros [0.0001, 0.0001, 0.0001, 128]: Model.fit() missing 1 required positional argument: 'self'

Empty DataFrame
Columns: [Parameters, AUC]
Index: []

## Shanghai

In [26]:
sequences = New_Sequences(Shanghai,minutes=15)
Randomized_Search_Results = pd.DataFrame(columns=['Parameters','AUC'])
for params in Parameters:
    l1_penalty, l2_penalty, learning_rate, batch_size = params
    try:
        R = Run_Models(sequences, l1_penalty,l2_penalty,learning_rate,batch_size, skf, Model)
        Randomized_Search_Results = pd.concat([Randomized_Search_Results, pd.DataFrame({
            'Parameters': [str(params)], 
            'AUC': [R]
        })], ignore_index=True)
    except Exception as e:
        print(f"Error con parámetros {params}: {e}")
        continue
Randomized_Search_Results.sort_values(by='AUC', ascending=False)

                        Parameters       AUC
102      [0.0001, 0.0001, 0.1, 16]      0.75
54         [0.001, 0.001, 0.1, 16]  0.714286
66        [0.001, 0.0001, 0.1, 16]  0.702381
7           [0.01, 0.01, 0.1, 128]  0.690476
4            [0.01, 0.01, 0.1, 64]  0.690476
5            [0.01, 0.01, 0.1, 32]  0.690476
42          [0.001, 0.01, 0.1, 16]  0.613095
67       [0.001, 0.0001, 0.1, 128]  0.607143
64        [0.001, 0.0001, 0.1, 64]  0.607143
65        [0.001, 0.0001, 0.1, 32]  0.607143
105   [0.0001, 0.0001, 0.0001, 32]  0.595238
44       [0.001, 0.01, 0.0001, 64]  0.595238
45       [0.001, 0.01, 0.0001, 32]  0.595238
47      [0.001, 0.01, 0.0001, 128]  0.595238
52         [0.001, 0.001, 0.1, 64]  0.595238
53         [0.001, 0.001, 0.1, 32]  0.595238
55        [0.001, 0.001, 0.1, 128]  0.595238
56      [0.001, 0.001, 0.0001, 64]  0.595238
57      [0.001, 0.001, 0.0001, 32]  0.595238
59     [0.001, 0.001, 0.0001, 128]  0.595238
104   [0.0001, 0.0001, 0.0001, 64]  0.595238
95    [0.0001, 0.001, 0.0001, 128]  0.595238
68     [0.001, 0.0001, 0.0001, 64]  0.595238
69     [0.001, 0.0001, 0.0001, 32]  0.595238
35     [0.01, 0.0001, 0.0001, 128]  0.595238
80      [0.0001, 0.01, 0.0001, 64]  0.595238
81      [0.0001, 0.01, 0.0001, 32]  0.595238
83     [0.0001, 0.01, 0.0001, 128]  0.595238
88        [0.0001, 0.001, 0.1, 64]  0.595238
89        [0.0001, 0.001, 0.1, 32]  0.595238
91       [0.0001, 0.001, 0.1, 128]  0.595238
92     [0.0001, 0.001, 0.0001, 64]  0.595238
93     [0.0001, 0.001, 0.0001, 32]  0.595238
71    [0.001, 0.0001, 0.0001, 128]  0.595238
107  [0.0001, 0.0001, 0.0001, 128]  0.595238
9         [0.01, 0.01, 0.0001, 32]  0.595238
8         [0.01, 0.01, 0.0001, 64]  0.595238
18          [0.01, 0.001, 0.1, 16]  0.595238
20       [0.01, 0.001, 0.0001, 64]  0.595238
21       [0.01, 0.001, 0.0001, 32]  0.595238
23      [0.01, 0.001, 0.0001, 128]  0.595238
33      [0.01, 0.0001, 0.0001, 32]  0.595238
32      [0.01, 0.0001, 0.0001, 64]  0.595238
11       [0.01, 0.01, 0.0001, 128]  0.595238
30         [0.01, 0.0001, 0.1, 16]  0.583333
22       [0.01, 0.001, 0.0001, 16]  0.559524
90        [0.0001, 0.001, 0.1, 16]  0.559524
10        [0.01, 0.01, 0.0001, 16]  0.559524
34      [0.01, 0.0001, 0.0001, 16]  0.559524
103     [0.0001, 0.0001, 0.1, 128]  0.559524
101      [0.0001, 0.0001, 0.1, 32]  0.559524
100      [0.0001, 0.0001, 0.1, 64]  0.559524
79        [0.0001, 0.01, 0.1, 128]  0.541667
77         [0.0001, 0.01, 0.1, 32]  0.541667
76         [0.0001, 0.01, 0.1, 64]  0.541667
6            [0.01, 0.01, 0.1, 16]   0.52381
58      [0.001, 0.001, 0.0001, 16]   0.52381
46       [0.001, 0.01, 0.0001, 16]   0.52381
70     [0.001, 0.0001, 0.0001, 16]   0.52381
31        [0.01, 0.0001, 0.1, 128]  0.494048
28         [0.01, 0.0001, 0.1, 64]  0.494048
29         [0.01, 0.0001, 0.1, 32]  0.494048
94     [0.0001, 0.001, 0.0001, 16]  0.488095
106   [0.0001, 0.0001, 0.0001, 16]  0.488095
82      [0.0001, 0.01, 0.0001, 16]  0.488095
14        [0.01, 0.001, 1e-06, 16]   0.47619
84      [0.0001, 0.001, 1e-06, 64]   0.47619
85      [0.0001, 0.001, 1e-06, 32]   0.47619
86      [0.0001, 0.001, 1e-06, 16]   0.47619
99    [0.0001, 0.0001, 1e-06, 128]   0.47619
87     [0.0001, 0.001, 1e-06, 128]   0.47619
2          [0.01, 0.01, 1e-06, 16]   0.47619
3         [0.01, 0.01, 1e-06, 128]   0.47619
98     [0.0001, 0.0001, 1e-06, 16]   0.47619
13        [0.01, 0.001, 1e-06, 32]   0.47619
12        [0.01, 0.001, 1e-06, 64]   0.47619
96     [0.0001, 0.0001, 1e-06, 64]   0.47619
97     [0.0001, 0.0001, 1e-06, 32]   0.47619
15       [0.01, 0.001, 1e-06, 128]   0.47619
0          [0.01, 0.01, 1e-06, 64]   0.47619
26       [0.01, 0.0001, 1e-06, 16]   0.47619
60      [0.001, 0.0001, 1e-06, 64]   0.47619
48       [0.001, 0.001, 1e-06, 64]   0.47619
49       [0.001, 0.001, 1e-06, 32]   0.47619
50       [0.001, 0.001, 1e-06, 16]   0.47619
51      [0.001, 0.001, 1e-06, 128]   0.47619
1          [0.01, 0.01, 1e-06, 32]   0.47619
27      [0.01, 0.0001, 1e-06, 128]   0.47619
38        [0.001, 0.01, 1e-06, 16]   0.47619
25       [0.01, 0.0001, 1e-06, 32]   0.47619
39       [0.001, 0.01, 1e-06, 128]   0.47619
24       [0.01, 0.0001, 1e-06, 64]   0.47619
61      [0.001, 0.0001, 1e-06, 32]   0.47619
62      [0.001, 0.0001, 1e-06, 16]   0.47619
63     [0.001, 0.0001, 1e-06, 128]   0.47619
37        [0.001, 0.01, 1e-06, 32]   0.47619
36        [0.001, 0.01, 1e-06, 64]   0.47619
72       [0.0001, 0.01, 1e-06, 64]   0.47619
73       [0.0001, 0.01, 1e-06, 32]   0.47619
74       [0.0001, 0.01, 1e-06, 16]   0.47619
75      [0.0001, 0.01, 1e-06, 128]   0.47619
43         [0.001, 0.01, 0.1, 128]  0.416667
41          [0.001, 0.01, 0.1, 32]  0.416667
40          [0.001, 0.01, 0.1, 64]  0.416667
16          [0.01, 0.001, 0.1, 64]  0.410714
19         [0.01, 0.001, 0.1, 128]  0.410714
17          [0.01, 0.001, 0.1, 32]  0.410714
78         [0.0001, 0.01, 0.1, 16]  0.363095