In [ ]:
from src.dataset_loader import Replace, AIDE, Granada, sequences_Replace, night_sequences_Replace, sequences_AIDE, night_sequences_AIDE, sequences_Granada, night_sequences_Granada
from src.utils import get_sequences
import pandas as pd
import numpy as np

Processing raw Granada data...
--- Granada cached to cache\Granada.parquet ---

In [ ]:
def generate_comparison_table(datasets_info):
    """
    datasets_info: List of tuples [(dataframe, sequences, "Name"), ...]
    """
    all_stats = []
    
    for data, sequences, name in datasets_info:
        samples_per_patient = data.groupby('id').size()
        y_labels = [s['Y'] for s in sequences]
        
        # Calculate TIR metrics per patient
        patient_metrics = data.groupby('id')['gl'].apply(lambda x: pd.Series({
            'tb54': (x < 54).mean() * 100,
            'tb70': (x < 70).mean() * 100,
            'tir': ((x >= 70) & (x <= 180)).mean() * 100,
            'ta180': (x > 180).mean() * 100,
            'ta250': (x > 250).mean() * 100
        })).unstack()

        stats = {
            "Metric": name,
            "Number of patients": data['id'].nunique(),
            "Number of samples per patient (min-max)": f"{samples_per_patient.min()} - {samples_per_patient.max()}",
            "Number of samples per patient (mean ± SD)": f"{samples_per_patient.mean():.2f} (±{samples_per_patient.std():.2f})",
            "Total sequences": len(sequences),
            "Positive labelled (Y=1)": sum(y_labels),
            "Negative labelled (Y=0)": len(y_labels) - sum(y_labels),
            "Glucose min-max": f"{data['gl'].min()} - {data['gl'].max()}",
            "Glucose mean (SD)": f"{data['gl'].mean():.2f} (±{data['gl'].std():.2f})",
            "Time Below 54 mg/dL (%)": f"{patient_metrics['tb54'].mean():.2f}% (±{patient_metrics['tb54'].std():.2f})",
            "Time Below 70 mg/dL (%)": f"{patient_metrics['tb70'].mean():.2f}% (±{patient_metrics['tb70'].std():.2f})",
            "Time In Range 70-180 mg/dL (%)": f"{patient_metrics['tir'].mean():.2f}% (±{patient_metrics['tir'].std():.2f})",
            "Time Above 180 mg/dL (%)": f"{patient_metrics['ta180'].mean():.2f}% (±{patient_metrics['ta180'].std():.2f})",
            "Time Above 250 mg/dL (%)": f"{patient_metrics['ta250'].mean():.2f}% (±{patient_metrics['ta250'].std():.2f})"

            #agregar cuantas lecturas tienen las secuencias (promedio, minimo, maximo, deviacion estandar)
            #agregar numero de secuencias inciales y el numero de secuencias eliminadas
        }
        all_stats.append(stats)
    
    # Transpose for the final look
    return pd.DataFrame(all_stats).set_index("Metric").T

## Replace

In [ ]:
generate_comparison_table([(Replace, sequences_Replace, "Replace Dataset")])

Generating Replace (general) sequences in parallel...
Done. Sequences saved to cache\seq_Replace_general_5min.joblib

Metric                                          Replace Dataset
Number of patients                                          226
Number of samples per patient (min-max)           15832 - 94021
Number of samples per patient (mean ± SD)  65143.08 (±10686.21)
Total sequences                                            6829
Positive labelled (Y=1)                                    2713
Negative labelled (Y=0)                                    4116
Glucose min-max                                    40.0 - 400.0
Glucose mean (SD)                               159.80 (±63.06)
Time Below 54 mg/dL (%)                           0.76% (±0.67)
Time Below 70 mg/dL (%)                           3.58% (±2.34)
Time In Range 70-180 mg/dL (%)                  63.42% (±12.04)
Time Above 180 mg/dL (%)                        33.00% (±12.82)
Time Above 250 mg/dL (%)                          9.42% (±6.99)

In [ ]:
generate_comparison_table([(Replace, night_sequences_Replace, "Replace Dataset (Night)")])

Generating Replace (night) sequences in parallel...
Done. Sequences saved to cache\seq_Replace_night_5min.joblib

Metric                                    Replace Dataset (Night)
Number of patients                                            226
Number of samples per patient (min-max)             15832 - 94021
Number of samples per patient (mean ± SD)    65143.08 (±10686.21)
Total sequences                                              6829
Positive labelled (Y=1)                                      1805
Negative labelled (Y=0)                                      5024
Glucose min-max                                      40.0 - 400.0
Glucose mean (SD)                                 159.80 (±63.06)
Time Below 54 mg/dL (%)                             0.76% (±0.67)
Time Below 70 mg/dL (%)                             3.58% (±2.34)
Time In Range 70-180 mg/dL (%)                    63.42% (±12.04)
Time Above 180 mg/dL (%)                          33.00% (±12.82)
Time Above 250 mg/dL (%)                            9.42% (±6.99)

## AIDE

In [ ]:
generate_comparison_table([(AIDE, sequences_AIDE, "AIDE Dataset")])

Generating AIDE (general) sequences in parallel...
Done. Sequences saved to cache\seq_AIDE_general_5min.joblib

Metric                                             AIDE Dataset
Number of patients                                           29
Number of samples per patient (min-max)             237 - 62408
Number of samples per patient (mean ± SD)  16520.41 (±15793.31)
Total sequences                                             174
Positive labelled (Y=1)                                      43
Negative labelled (Y=0)                                     131
Glucose min-max                                    40.0 - 400.0
Glucose mean (SD)                               153.22 (±60.65)
Time Below 54 mg/dL (%)                           0.53% (±0.72)
Time Below 70 mg/dL (%)                           2.83% (±2.66)
Time In Range 70-180 mg/dL (%)                  66.80% (±14.12)
Time Above 180 mg/dL (%)                        30.38% (±14.84)
Time Above 250 mg/dL (%)                          8.67% (±8.64)

In [ ]:
generate_comparison_table([(AIDE, night_sequences_AIDE, "AIDE Dataset (Night)")])

Generating AIDE (night) sequences in parallel...
Done. Sequences saved to cache\seq_AIDE_night_5min.joblib

Metric                                     AIDE Dataset (Night)
Number of patients                                           29
Number of samples per patient (min-max)             237 - 62408
Number of samples per patient (mean ± SD)  16520.41 (±15793.31)
Total sequences                                             174
Positive labelled (Y=1)                                      27
Negative labelled (Y=0)                                     147
Glucose min-max                                    40.0 - 400.0
Glucose mean (SD)                               153.22 (±60.65)
Time Below 54 mg/dL (%)                           0.53% (±0.72)
Time Below 70 mg/dL (%)                           2.83% (±2.66)
Time In Range 70-180 mg/dL (%)                  66.80% (±14.12)
Time Above 180 mg/dL (%)                        30.38% (±14.84)
Time Above 250 mg/dL (%)                          8.67% (±8.64)

## Granada

In [ ]:
generate_comparison_table([(Granada, sequences_Granada, "Granada Dataset")])

Generating Granada (general) sequences in parallel...
Done. Sequences saved to cache\seq_Granada_general_15min.joblib

Metric                                          Granada Dataset
Number of patients                                          736
Number of samples per patient (min-max)            347 - 137042
Number of samples per patient (mean ± SD)  30579.05 (±25528.36)
Total sequences                                           29896
Positive labelled (Y=1)                                   11504
Negative labelled (Y=0)                                   18392
Glucose min-max                                        40 - 400
Glucose mean (SD)                               162.69 (±67.45)
Time Below 54 mg/dL (%)                           0.90% (±1.45)
Time Below 70 mg/dL (%)                           4.45% (±4.11)
Time In Range 70-180 mg/dL (%)                  58.82% (±15.32)
Time Above 180 mg/dL (%)                        36.73% (±16.15)
Time Above 250 mg/dL (%)                        12.52% (±10.84)

In [ ]:
generate_comparison_table([(Granada, night_sequences_Granada, "Granada Dataset (Night)")])

Generating Granada (night) sequences in parallel...
Done. Sequences saved to cache\seq_Granada_night_15min.joblib

Metric                                    Granada Dataset (Night)
Number of patients                                            736
Number of samples per patient (min-max)              347 - 137042
Number of samples per patient (mean ± SD)    30579.05 (±25528.36)
Total sequences                                             29896
Positive labelled (Y=1)                                      7184
Negative labelled (Y=0)                                     22712
Glucose min-max                                          40 - 400
Glucose mean (SD)                                 162.69 (±67.45)
Time Below 54 mg/dL (%)                             0.90% (±1.45)
Time Below 70 mg/dL (%)                             4.45% (±4.11)
Time In Range 70-180 mg/dL (%)                    58.82% (±15.32)
Time Above 180 mg/dL (%)                          36.73% (±16.15)
Time Above 250 mg/dL (%)                          12.52% (±10.84)

describir cuantos eventos suceden al inicio de la secuencia y si vienen de la semana anterior, cuantas horas puede durar un evento
verlo en una grafica si los eventos de la semana anterior pasan a la siguiente

regresion multiclase = no hubo evento, el evento fue en la noche, el evento fue en el dia

regresion logistica multimodal

cambiamos la funcion de activacion por softmax
regularizcion sería lo mismo
cambiamos la funcion de perdida = por una multiclase
tener un peso por clases, mayor peso para la clase nocturna (weights)